### ISSUE TITLE
New version required

### ISSUE THREAD

**Issue by overbost** [QuaererePlatform/Flask-arango-orm#10]
Hi mantainers,
@ravenoak @vx-git-robot 

the project is old and compatible with python-arango <= 4.x but the latest python-arango version in 7.x.

Can someone update this project?

The main change to do is the connection with ArangoClient (the init change since 4.x version)

Thanks

**Comment by overbost** [comment]
Check out PR #11 
@ravenoak @vx-git-robot

**Comment by ravenoak** [comment]
Hi Loris,

I've merged your PR and I apologize for not seeing this sooner! I'll also
need to verify that the CI/CD pipeline is still working as well. I haven't
needed this project in a while, so thank you for taking the time to update
it!

Thank you,
Caitlyn O'Hanna

**Comment by ravenoak** [comment]
It seems I've merged in this PR a little too hastily. This project had been managed using a git-flow style workflow and the CI/CD pipeline had been managing the version increments based on that flow. I'll either need to revert the PR and have it applied to the `develop` branch, or I'll need to rework the pipeline. At worst case I can do a manual release once I get the credentials rounded up and fix the pipeline later.

I'll try to get this done as soon as possible.

**Comment by overbost** [comment]
Please check out tests code. I must edit it to test, there are some dirty comments.
My PR is not very clean, if you want make your PR with my edits.

**Comment by ravenoak** [comment]
Released 0.2.0
